<?php
//主机地址，默认为localhost,默认端口为3306,可添加端口号，例如localhost:8888
define('mysql_servername','localhost'); 
//数据库用户名
define('mysql_username','FnB'); 
//数据库密码
define('mysql_password','1091044631');
//数据库名
define('mysql_database','FnB'); 
?>